// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type CreateNoteInput struct {
	EncryptedTitle   string  `json:"encryptedTitle"`
	EncryptedContent string  `json:"encryptedContent"`
	EncryptedFolder  *string `json:"encryptedFolder,omitempty"`
	EncryptedTags    *string `json:"encryptedTags,omitempty"`
	ContentHash      string  `json:"contentHash"`
	ByteSize         int     `json:"byteSize"`
	Pinned           *bool   `json:"pinned,omitempty"`
}

type EncryptedNote struct {
	ID               string  `json:"id"`
	EncryptedTitle   string  `json:"encryptedTitle"`
	EncryptedContent string  `json:"encryptedContent"`
	EncryptedFolder  *string `json:"encryptedFolder,omitempty"`
	EncryptedTags    *string `json:"encryptedTags,omitempty"`
	ContentHash      string  `json:"contentHash"`
	ByteSize         int     `json:"byteSize"`
	Pinned           bool    `json:"pinned"`
	Deleted          bool    `json:"deleted"`
	DeletedAt        *string `json:"deletedAt,omitempty"`
	CreatedAt        string  `json:"createdAt"`
	UpdatedAt        string  `json:"updatedAt"`
	SyncedAt         *string `json:"syncedAt,omitempty"`
}

type SetupVaultInput struct {
	EncryptedVaultKey    string `json:"encryptedVaultKey"`
	Argon2Memory         int    `json:"argon2Memory"`
	Argon2Iterations     int    `json:"argon2Iterations"`
	Argon2Parallelism    int    `json:"argon2Parallelism"`
	Argon2Salt           string `json:"argon2Salt"`
	EncryptedRecoveryKey string `json:"encryptedRecoveryKey"`
	RecoveryKeySalt      string `json:"recoveryKeySalt"`
}

type SyncResult struct {
	Notes      []*EncryptedNote `json:"notes"`
	DeletedIds []string         `json:"deletedIds"`
	ServerTime string           `json:"serverTime"`
}

type UpdateNoteInput struct {
	EncryptedTitle   *string `json:"encryptedTitle,omitempty"`
	EncryptedContent *string `json:"encryptedContent,omitempty"`
	EncryptedFolder  *string `json:"encryptedFolder,omitempty"`
	EncryptedTags    *string `json:"encryptedTags,omitempty"`
	ContentHash      *string `json:"contentHash,omitempty"`
	ByteSize         *int    `json:"byteSize,omitempty"`
	Pinned           *bool   `json:"pinned,omitempty"`
}

type User struct {
	ID          string       `json:"id"`
	Email       string       `json:"email"`
	VaultConfig *VaultConfig `json:"vaultConfig,omitempty"`
	NoteCount   int          `json:"noteCount"`
	CreatedAt   string       `json:"createdAt"`
}

type VaultConfig struct {
	ID                   string `json:"id"`
	EncryptedVaultKey    string `json:"encryptedVaultKey"`
	Argon2Memory         int    `json:"argon2Memory"`
	Argon2Iterations     int    `json:"argon2Iterations"`
	Argon2Parallelism    int    `json:"argon2Parallelism"`
	Argon2Salt           string `json:"argon2Salt"`
	EncryptedRecoveryKey string `json:"encryptedRecoveryKey"`
	RecoveryKeySalt      string `json:"recoveryKeySalt"`
	CreatedAt            string `json:"createdAt"`
	UpdatedAt            string `json:"updatedAt"`
}
