package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"
	"time"

	"github.com/Zubimendi/securememo/internal/auth"
	"github.com/Zubimendi/securememo/internal/store"
)

// ─── HELPERS: store ↔ GraphQL model conversion ──────────────────────────────

func noteToGQL(n *store.Note) *EncryptedNote {
	if n == nil {
		return nil
	}
	gql := &EncryptedNote{
		ID:               n.ID,
		EncryptedTitle:   n.EncryptedTitle,
		EncryptedContent: n.EncryptedContent,
		EncryptedFolder:  n.EncryptedFolder,
		EncryptedTags:    n.EncryptedTags,
		ContentHash:      n.ContentHash,
		ByteSize:         n.ByteSize,
		Pinned:           n.Pinned,
		Deleted:          n.Deleted,
		CreatedAt:        n.CreatedAt.Format(time.RFC3339),
		UpdatedAt:        n.UpdatedAt.Format(time.RFC3339),
	}
	if n.DeletedAt != nil {
		s := n.DeletedAt.Format(time.RFC3339)
		gql.DeletedAt = &s
	}
	if n.SyncedAt != nil {
		s := n.SyncedAt.Format(time.RFC3339)
		gql.SyncedAt = &s
	}
	return gql
}

func notesToGQL(notes []*store.Note) []*EncryptedNote {
	out := make([]*EncryptedNote, len(notes))
	for i, n := range notes {
		out[i] = noteToGQL(n)
	}
	return out
}

func vaultConfigToGQL(cfg *store.VaultConfig) *VaultConfig {
	if cfg == nil {
		return nil
	}
	return &VaultConfig{
		ID:                   cfg.ID,
		EncryptedVaultKey:    cfg.EncryptedVaultKey,
		Argon2Memory:         cfg.Argon2Memory,
		Argon2Iterations:     cfg.Argon2Iterations,
		Argon2Parallelism:    cfg.Argon2Parallelism,
		Argon2Salt:           cfg.Argon2Salt,
		EncryptedRecoveryKey: cfg.EncryptedRecoveryKey,
		RecoveryKeySalt:      cfg.RecoveryKeySalt,
		CreatedAt:            cfg.CreatedAt.Format(time.RFC3339),
		UpdatedAt:            cfg.UpdatedAt.Format(time.RFC3339),
	}
}

// ─── QUERY RESOLVERS ────────────────────────────────────────────────────────

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*User, error) {
	userID, err := auth.UserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	count, _ := r.Store.GetNoteCount(ctx, userID)
	// Try to get vault config for the user
	cfg, _ := r.Store.GetVaultConfig(ctx, userID)
	var gqlCfg *VaultConfig
	if cfg != nil {
		gqlCfg = vaultConfigToGQL(cfg)
	}
	email := auth.UserEmailFromContext(ctx)
	
	createdAt := time.Now().Format(time.RFC3339)
	if cfg != nil {
		createdAt = cfg.CreatedAt.Format(time.RFC3339)
	}

	return &User{
		ID:          userID,
		Email:       email,
		VaultConfig: gqlCfg,
		NoteCount:   count,
		CreatedAt:   createdAt,
	}, nil
}

// VaultConfig is the resolver for the vaultConfig field.
func (r *queryResolver) VaultConfig(ctx context.Context) (*VaultConfig, error) {
	userID, err := auth.UserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	cfg, err := r.Store.GetVaultConfig(ctx, userID)
	if err != nil {
		return nil, err
	}
	return vaultConfigToGQL(cfg), nil
}

// Notes is the resolver for the notes field.
func (r *queryResolver) Notes(ctx context.Context, limit *int, offset *int, includeDeleted *bool) ([]*EncryptedNote, error) {
	userID, err := auth.UserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	l, o, id := 50, 0, false
	if limit != nil {
		l = *limit
	}
	if offset != nil {
		o = *offset
	}
	if includeDeleted != nil {
		id = *includeDeleted
	}
	notes, err := r.Store.ListNotes(ctx, userID, l, o, id)
	if err != nil {
		return nil, err
	}
	return notesToGQL(notes), nil
}

// Note is the resolver for the note field.
func (r *queryResolver) Note(ctx context.Context, id string) (*EncryptedNote, error) {
	userID, err := auth.UserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	n, err := r.Store.GetNote(ctx, userID, id)
	if err != nil {
		return nil, err
	}
	return noteToGQL(n), nil
}

// SyncNotes is the resolver for the syncNotes field.
func (r *queryResolver) SyncNotes(ctx context.Context, since string) (*SyncResult, error) {
	userID, err := auth.UserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	t, err := time.Parse(time.RFC3339, since)
	if err != nil {
		return nil, err
	}
	notes, deletedIDs, err := r.Store.SyncNotes(ctx, userID, t)
	if err != nil {
		return nil, err
	}
	return &SyncResult{
		Notes:      notesToGQL(notes),
		DeletedIds: deletedIDs,
		ServerTime: time.Now().Format(time.RFC3339),
	}, nil
}

// ─── MUTATION RESOLVERS ─────────────────────────────────────────────────────

// SetupVault is the resolver for the setupVault field.
func (r *mutationResolver) SetupVault(ctx context.Context, input SetupVaultInput) (*VaultConfig, error) {
	userID, err := auth.UserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	cfg := store.VaultConfig{
		UserID:               userID,
		EncryptedVaultKey:    input.EncryptedVaultKey,
		Argon2Memory:         input.Argon2Memory,
		Argon2Iterations:     input.Argon2Iterations,
		Argon2Parallelism:    input.Argon2Parallelism,
		Argon2Salt:           input.Argon2Salt,
		EncryptedRecoveryKey: input.EncryptedRecoveryKey,
		RecoveryKeySalt:      input.RecoveryKeySalt,
	}
	result, err := r.Store.CreateVaultConfig(ctx, cfg)
	if err != nil {
		return nil, err
	}
	return vaultConfigToGQL(result), nil
}

// UpdateVaultConfig is the resolver for the updateVaultConfig field.
func (r *mutationResolver) UpdateVaultConfig(ctx context.Context, input SetupVaultInput) (*VaultConfig, error) {
	userID, err := auth.UserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	cfg := store.VaultConfig{
		UserID:               userID,
		EncryptedVaultKey:    input.EncryptedVaultKey,
		Argon2Memory:         input.Argon2Memory,
		Argon2Iterations:     input.Argon2Iterations,
		Argon2Parallelism:    input.Argon2Parallelism,
		Argon2Salt:           input.Argon2Salt,
		EncryptedRecoveryKey: input.EncryptedRecoveryKey,
		RecoveryKeySalt:      input.RecoveryKeySalt,
	}
	result, err := r.Store.UpdateVaultConfig(ctx, cfg)
	if err != nil {
		return nil, err
	}
	return vaultConfigToGQL(result), nil
}

// CreateNote is the resolver for the createNote field.
func (r *mutationResolver) CreateNote(ctx context.Context, input CreateNoteInput) (*EncryptedNote, error) {
	userID, err := auth.UserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	note := store.Note{
		UserID:           userID,
		EncryptedTitle:   input.EncryptedTitle,
		EncryptedContent: input.EncryptedContent,
		EncryptedFolder:  input.EncryptedFolder,
		EncryptedTags:    input.EncryptedTags,
		ContentHash:      input.ContentHash,
		ByteSize:         input.ByteSize,
		Pinned:           input.Pinned != nil && *input.Pinned,
	}
	result, err := r.Store.CreateNote(ctx, note)
	if err != nil {
		return nil, err
	}
	return noteToGQL(result), nil
}

// UpdateNote is the resolver for the updateNote field.
func (r *mutationResolver) UpdateNote(ctx context.Context, id string, input UpdateNoteInput) (*EncryptedNote, error) {
	userID, err := auth.UserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	note := store.Note{
		ID:     id,
		UserID: userID,
	}
	if input.EncryptedTitle != nil {
		note.EncryptedTitle = *input.EncryptedTitle
	}
	if input.EncryptedContent != nil {
		note.EncryptedContent = *input.EncryptedContent
	}
	if input.ContentHash != nil {
		note.ContentHash = *input.ContentHash
	}
	if input.ByteSize != nil {
		note.ByteSize = *input.ByteSize
	}
	note.EncryptedFolder = input.EncryptedFolder
	note.EncryptedTags = input.EncryptedTags
	if input.Pinned != nil {
		note.Pinned = *input.Pinned
	}
	result, err := r.Store.UpdateNote(ctx, note)
	if err != nil {
		return nil, err
	}
	return noteToGQL(result), nil
}

// DeleteNote is the resolver for the deleteNote field.
func (r *mutationResolver) DeleteNote(ctx context.Context, id string) (bool, error) {
	userID, err := auth.UserIDFromContext(ctx)
	if err != nil {
		return false, err
	}
	err = r.Store.SoftDeleteNote(ctx, userID, id)
	return err == nil, err
}

// PermanentlyDeleteNote is the resolver for the permanentlyDeleteNote field.
func (r *mutationResolver) PermanentlyDeleteNote(ctx context.Context, id string) (bool, error) {
	userID, err := auth.UserIDFromContext(ctx)
	if err != nil {
		return false, err
	}
	err = r.Store.HardDeleteNote(ctx, userID, id)
	return err == nil, err
}

// RestoreNote is the resolver for the restoreNote field.
func (r *mutationResolver) RestoreNote(ctx context.Context, id string) (bool, error) {
	userID, err := auth.UserIDFromContext(ctx)
	if err != nil {
		return false, err
	}
	err = r.Store.RestoreNote(ctx, userID, id)
	return err == nil, err
}

// EmptyTrash is the resolver for the emptyTrash field.
func (r *mutationResolver) EmptyTrash(ctx context.Context) (bool, error) {
	userID, err := auth.UserIDFromContext(ctx)
	if err != nil {
		return false, err
	}
	err = r.Store.EmptyTrash(ctx, userID)
	return err == nil, err
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
